spring.application.name=Sql-query-builder


# Role-based operations
whitelist.ADMIN.operations=SELECT,UPDATE,DELETE,INSERT
whitelist.USER.operations=SELECT

# Tables per role
whitelist.ADMIN.tables=users,orders,admin_logs
whitelist.USER.tables=users

# Columns per table per role
whitelist.ADMIN.users.columns=id,name,email,password
whitelist.ADMIN.orders.columns=id,amount,status

whitelist.USER.users.columns=id,name,email
whitelist.USER.orders.columns=id,amount


